### PR TITLE
Apply skolsons solution from #131 double to float operations as well.…

### LINKED ISSUE #134: BigDecimal floatValue and fromFloat have same bug as doubles had in issue #130
See the description of issue #130, the same exact bugs are in floatValue and fromFloat. Sorry I should have caught this during the issue 130 work,  Anyway while unit testing the fix to the two float functions I hit a different bug/feature and am unsure which it is - bug or feature.  Given this code snippet:
```
        f = BigDecimal.fromFloat(Float.MIN_VALUE)
        assertEquals(Float.MIN_VALUE, f.floatValue(true))
        val f2 = f.divide(BigDecimal.TEN)
```
The value of Float.MIN_VALUE is 1.4E-45.  As expected f2 is 1.4E-46.  But here is the state inside f2:
```
f2 = {BigDecimal@2111} "1.4E-46"
 precision = 11
 precisionLimit = 0
 roundingMode = {RoundingMode@1966} "NONE"
 significand = {BigInteger@1937} "14000000000"
 exponent = -46
 scale = -1
 usingScale = false
 decimalMode = {DecimalMode@1903} "DecimalMode(decimalPrecision=0, roundingMode=NONE, scale=-1)"
```
is the precision number and the significand correct in this case? Or should all those trailing zeroes have been trimmed and the precision set to 2?  If this is correct behavior lemme know, because there is current code in the narrowing stuff that expected this result to have precision = 2 and significand = 14.  Because it doesn't, the precision limit check in floatValue() is incorrect. And it likely there are cases where the doubleValue() precision limit check is incorrect for the same reason.  Both use the precision value in the same way as a limit check. 

Let me know what the correct behavior of precision and significand is in the above case, and I'll proceed from there to get fixes and unit tests developed for the above.

### PR DESCRIPTION
**Pull request by ionspin**
… This hopefully resolves #134

### CODE REVIEW

**Comment by ionspin** [comment]
I kinda blindly applied the solution for 131 here, it looks like it should work properly, but I would need @skolson to verify, and I'll try to look a bit more into it over weekend.

**Comment by ionspin** [comment]
Need to return the check if number can be expressed in IEEE 754

**Comment by ionspin** [comment]
So at this point it should be working correctly for normal numbers, but there needs to be a check for subnormal numbers.

**Comment by ionspin** [comment]
@skolson  If you have time to give this a glance, just to check if I missed anything obvious, otherwise I'd like to merge this to master this week. A fix for string parsing sneaked into this commit in the end, because exponent wasn't properly calculated when parsing mixed scientific notation and expanded such as 0.0000123E20 and 123E20 instead of pure scientific like 1.23E15 and 1.23E22 respectively.

**Comment by skolson** [comment]
I have one more commit with changes to BigDecimal.kt that removes the string massaging in fromFloat and fromDouble targeting trailing insignificant zeroes, and moves the trailing zero removal to parseStringWithMode.  I'll get that pushed up in a bit...

**Comment by skolson** [comment]
My git skills suck :-)  Can you look at my fork and the two commits (the one mentioned above, plus some additional tests) that I want to add to this pull request: [skolson fork](https://github.com/ionspin/kotlin-multiplatform-bignum/compare/master...skolson:master)?  If the changes in the comparison looks ok (tests pass), can you walk me through the git commands to add this to this pull request? I'm doing something wrong :-)

**Comment by skolson** [comment]
Cool!  Once the new stuff is in the snapshot I'll try it out. Ans I'll get my fork and local source synced up. Thanks!

**Pull request merged**
