### PR TITLE
Fix modInverse and or bitwise function

### PR DESCRIPTION
**Pull request by iTanChi**
Close issues:
- https://github.com/ionspin/kotlin-multiplatform-bignum/issues/289
- https://github.com/ionspin/kotlin-multiplatform-bignum/issues/290

The logic is updated and covered by unit test
We have also integrated it with our modules, and it works

### CODE REVIEW

**Comment by ionspin** [comment]
Thanks for the pull request, I'll look into it as soon as I have some free time!

**Comment by ionspin** [comment]
Why is there a github action definition in this pull request?

**Comment by iTanChi** [comment]
@ionspin our mistake when we want to publish a package for integrating into our module while waiting for your review. We are reverting that commit

**Comment by ionspin** [comment]
Ok, please clean up/squash the commits and open a new pull request. Thanks!

**Pull request closed without merging**
